# Generated by Django 6.0.3 on 2026-03-28 07:53

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_rename_notificatio_user_isread_idx_notificatio_user_id_c4e471_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_number', models.CharField(blank=True, db_index=True, max_length=20, unique=True, verbose_name='Investor Number')),
                ('odoo_investor_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Odoo Investor ID')),
                ('id_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('alien_id', 'Alien ID / Foreign Certificate')], default='national_id', max_length=20, verbose_name='ID Type')),
                ('id_number', models.CharField(blank=True, max_length=50, verbose_name='ID / Passport Number')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other / Prefer not to say')], max_length=10, verbose_name='Gender')),
                ('nationality', models.CharField(default='Kenyan', max_length=50, verbose_name='Nationality')),
                ('physical_address', models.TextField(blank=True, verbose_name='Physical Address')),
                ('county', models.CharField(blank=True, max_length=50, verbose_name='County')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Bank Name')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, verbose_name='Bank Account Number')),
                ('bank_branch', models.CharField(blank=True, max_length=100, verbose_name='Bank Branch')),
                ('mpesa_number', models.CharField(blank=True, max_length=15, verbose_name='M-Pesa Number')),
                ('preferred_payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('mpesa', 'M-Pesa')], default='mpesa', max_length=20, verbose_name='Preferred Payment Method')),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Complete'), ('complete', 'Complete — Awaiting Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20, verbose_name='KYC Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investor Profile',
                'verbose_name_plural': 'Investor Profiles',
                'db_table': 'investor_profiles',
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_number', models.CharField(blank=True, db_index=True, max_length=20, unique=True, verbose_name='Investment Number')),
                ('odoo_investment_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Odoo Investment ID')),
                ('investment_type', models.CharField(choices=[('fixed_term', 'Fixed Term'), ('open_ended', 'Open Ended')], default='fixed_term', max_length=20, verbose_name='Investment Type')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Principal Amount')),
                ('interest_rate', models.DecimalField(decimal_places=4, help_text='Annual rate as percentage e.g. 12.0000 for 12%', max_digits=6, verbose_name='Annual Interest Rate (%)')),
                ('compounding_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='monthly', max_length=20, verbose_name='Compounding Frequency')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('maturity_date', models.DateField(blank=True, null=True, verbose_name='Maturity Date')),
                ('state', models.CharField(choices=[('active', 'Active'), ('matured', 'Matured'), ('withdrawn', 'Withdrawn'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20, verbose_name='Status')),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Current Balance')),
                ('total_interest_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Interest Earned')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='loans.investorprofile')),
            ],
            options={
                'verbose_name': 'Investment',
                'verbose_name_plural': 'Investments',
                'db_table': 'investor_investments',
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('interest_credit', 'Interest Credit'), ('penalty', 'Penalty'), ('adjustment', 'Adjustment')], db_index=True, max_length=20, verbose_name='Transaction Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Amount')),
                ('reference', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Reference')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='completed', max_length=20, verbose_name='Status')),
                ('transaction_date', models.DateField(default=django.utils.timezone.now, verbose_name='Transaction Date')),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Balance After')),
                ('odoo_transaction_id', models.IntegerField(blank=True, null=True, verbose_name='Odoo Transaction ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='loans.investment')),
            ],
            options={
                'verbose_name': 'Investment Transaction',
                'verbose_name_plural': 'Investment Transactions',
                'db_table': 'investor_transactions',
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['investment', 'transaction_type'], name='investor_tr_investm_fc173b_idx'), models.Index(fields=['transaction_date'], name='investor_tr_transac_b3a14c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['investor', 'state'], name='investor_in_investo_d901ff_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['investment_number'], name='investor_in_investm_d4ff46_idx'),
        ),
    ]
